---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.label.deployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.label.template }}
  template:
    metadata:
      labels:
        name: {{ .Values.label.template }}
        author: {{ .Values.author }}
    spec:
      containers:
        - name: docker-minio-api-k8s
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8090
          env:
          - name: END_POINT 
            value: "192.168.97.48:59000"
          - name: API_KEY
            value: "123456789"
          - name: SECRET_KEY 
            value: "123456789"